/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Аутентификация пользователя
         * @description Проксирование в UOM. Возвращает JWT access token и refresh token.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновление access token */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Выход из системы
         * @description Отзывает refresh token в UOM.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Загрузка нового договора
         * @description Загрузка PDF-файла договора. Оркестратор:
         *     1. Валидирует файл (размер, формат).
         *     2. Загружает в Object Storage.
         *     3. Создаёт документ и версию в DM.
         *     4. Публикует команду на обработку в DP.
         *     Возвращает 202 Accepted — обработка асинхронная.
         */
        post: operations["uploadContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список договоров организации */
        get: operations["listContracts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Детали договора
         * @description Возвращает метаданные договора с текущей версией и user-friendly статусом.
         */
        get: operations["getContract"];
        put?: never;
        post?: never;
        /** Удаление договора (soft delete) */
        delete: operations["deleteContract"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Архивация договора */
        post: operations["archiveContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список версий договора */
        get: operations["listVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}/versions/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Загрузка новой версии существующего договора
         * @description Загрузка новой редакции (RE_UPLOAD). Создаёт новую версию и запускает обработку.
         */
        post: operations["uploadNewVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Детали версии */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}/versions/{version_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Статус обработки версии (polling fallback)
         * @description Альтернатива SSE для получения текущего статуса обработки.
         */
        get: operations["getVersionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}/versions/{version_id}/recheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Повторная проверка версии (UR-9)
         * @description Создаёт новую версию с origin_type=RE_CHECK (тот же файл, новый анализ).
         */
        post: operations["recheckVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}/versions/{version_id}/confirm-type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Подтверждение типа договора при низкой уверенности (UR-3 / FR-2.1.3)
         * @description Возобновляет обработку версии, остановленной в статусе AWAITING_USER_INPUT.
         *     Вызывается пользователем после получения SSE-события `type_confirmation_required`.
         *
         *     Контракт:
         *     - Тело запроса: `{contract_type, confirmed_by_user: true}`. `contract_type` —
         *       либо `suggested_type` из события, либо одно из значений `alternatives[].contract_type`,
         *       либо произвольный валидный тип (контролируется LIC).
         *     - Версия должна находиться в статусе `AWAITING_USER_INPUT`. Иначе — 409
         *       с error_code `VERSION_NOT_AWAITING_INPUT`.
         *     - После успешного вызова Orchestrator публикует команду `UserConfirmedType`
         *       в LIC и переводит версию в `ANALYZING`.
         *
         *     По истечении `ORCH_USER_CONFIRMATION_TIMEOUT` (default 24h) без подтверждения
         *     версия автоматически переводится в `FAILED` с error_code `USER_CONFIRMATION_TIMEOUT`
         *     (watchdog оркестратора).
         */
        post: operations["confirmContractType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}/versions/{version_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Агрегированные результаты проверки
         * @description Возвращает все результаты анализа для версии: риски, рекомендации, резюме,
         *     ключевые параметры, тип договора, сводная оценка. Фильтруется по роли пользователя.
         *     R-2 (бизнес-пользователь) видит только summary и aggregate_score.
         */
        get: operations["getResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}/versions/{version_id}/risks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список рисков (UR-4, UR-5) */
        get: operations["getRisks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}/versions/{version_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Краткое резюме (UR-7) */
        get: operations["getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}/versions/{version_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Рекомендации формулировок (UR-6) */
        get: operations["getRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Запуск сравнения версий (FR-5.3.1) */
        post: operations["compareVersions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}/versions/{base_version_id}/diff/{target_version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Результат сравнения версий */
        get: operations["getDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}/versions/{version_id}/export/{format}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Экспорт отчёта (UR-10) */
        get: operations["exportReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}/versions/{version_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обратная связь по результатам (UR-11) */
        post: operations["submitFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список политик организации (UR-12) */
        get: operations["listPolicies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/policies/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Обновление политики */
        put: operations["updatePolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/checklists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список чек-листов организации */
        get: operations["listChecklists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/checklists/{checklist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Обновление чек-листа */
        put: operations["updateChecklist"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE-поток статусных обновлений
         * @description Server-Sent Events endpoint для real-time получения статусов обработки.
         *     Аутентификация через query parameter `token` (SSE EventSource API не поддерживает кастомные заголовки).
         *     Heartbeat `:ping` каждые 15 секунд.
         *     Автоматическое переподключение встроено в браузерный EventSource API.
         */
        get: operations["eventStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Профиль текущего пользователя
         * @description Проксирование в UOM.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        AuthTokens: {
            /** @description JWT access token (TTL 15 минут) */
            access_token?: string;
            /** @description Refresh token (TTL 30 дней) */
            refresh_token?: string;
            /** @description Время жизни access token в секундах */
            expires_in?: number;
        };
        /** @enum {string} */
        DocumentStatus: "ACTIVE" | "ARCHIVED" | "DELETED";
        /**
         * @description User-friendly статус обработки:
         *     - UPLOADED — договор загружен
         *     - QUEUED — в очереди на обработку
         *     - PROCESSING — извлечение текста и структуры
         *     - ANALYZING — юридический анализ
         *     - AWAITING_USER_INPUT — пайплайн остановлен в ожидании подтверждения пользователя (FR-2.1.3): тип договора определён с низкой уверенностью, требуется выбор/подтверждение через POST /contracts/{contract_id}/versions/{version_id}/confirm-type. Из этого статуса возможны переходы только в ANALYZING (после подтверждения) или FAILED (по таймауту, ORCH_USER_CONFIRMATION_TIMEOUT).
         *     - GENERATING_REPORTS — формирование отчётов
         *     - READY — результаты готовы
         *     - PARTIALLY_FAILED — частично доступно (есть ошибки)
         *     - FAILED — ошибка обработки
         *     - REJECTED — файл отклонён
         * @enum {string}
         */
        UserProcessingStatus: "UPLOADED" | "QUEUED" | "PROCESSING" | "ANALYZING" | "AWAITING_USER_INPUT" | "GENERATING_REPORTS" | "READY" | "PARTIALLY_FAILED" | "FAILED" | "REJECTED";
        UploadResponse: {
            /**
             * Format: uuid
             * @description ID договора (document_id в DM)
             */
            contract_id?: string;
            /** Format: uuid */
            version_id?: string;
            version_number?: number;
            /**
             * Format: uuid
             * @description ID задачи обработки (для tracking)
             */
            job_id?: string;
            status?: components["schemas"]["UserProcessingStatus"];
            /** @description Статус на русском языке */
            message?: string;
        };
        ConfirmTypeRequest: {
            /**
             * @description Подтверждённый пользователем тип договора (e.g. "услуги", "поставка", "подряд",
             *     "аренда", "NDA"). Whitelist валидных значений контролируется LIC; передача
             *     значения вне whitelist приводит к 400 VALIDATION_ERROR.
             * @example услуги
             */
            contract_type: string;
            /**
             * @description Маркер того, что выбор сделан пользователем явно (а не системой). Должен быть `true` — иначе 400.
             * @example true
             */
            confirmed_by_user: boolean;
        };
        ContractSummary: {
            /** Format: uuid */
            contract_id?: string;
            title?: string;
            status?: components["schemas"]["DocumentStatus"];
            current_version_number?: number | null;
            processing_status?: components["schemas"]["UserProcessingStatus"];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ContractList: {
            items?: components["schemas"]["ContractSummary"][];
            total?: number;
            page?: number;
            size?: number;
        };
        ContractDetails: {
            /** Format: uuid */
            contract_id?: string;
            title?: string;
            status?: components["schemas"]["DocumentStatus"];
            current_version?: components["schemas"]["VersionDetails"];
            /** Format: uuid */
            created_by_user_id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        /** @enum {string} */
        OriginType: "UPLOAD" | "RE_UPLOAD" | "RECOMMENDATION_APPLIED" | "MANUAL_EDIT" | "RE_CHECK";
        VersionDetails: {
            /** Format: uuid */
            version_id?: string;
            /** Format: uuid */
            contract_id?: string;
            version_number?: number;
            origin_type?: components["schemas"]["OriginType"];
            origin_description?: string | null;
            /** Format: uuid */
            parent_version_id?: string | null;
            source_file_name?: string;
            /** Format: int64 */
            source_file_size?: number;
            processing_status?: components["schemas"]["UserProcessingStatus"];
            /** @description Статус на русском языке */
            processing_status_message?: string;
            /** Format: date-time */
            created_at?: string;
        };
        VersionList: {
            items?: components["schemas"]["VersionDetails"][];
            total?: number;
            page?: number;
            size?: number;
        };
        ProcessingStatus: {
            /** Format: uuid */
            version_id?: string;
            status?: components["schemas"]["UserProcessingStatus"];
            /** @description Статус на русском языке */
            message?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        AnalysisResults: {
            /** Format: uuid */
            version_id?: string;
            status?: components["schemas"]["UserProcessingStatus"];
            contract_type?: components["schemas"]["ClassificationResult"];
            key_parameters?: components["schemas"]["KeyParameters"];
            risk_profile?: components["schemas"]["RiskProfile"];
            risks?: components["schemas"]["Risk"][] | null;
            recommendations?: components["schemas"]["Recommendation"][] | null;
            /** @description Краткое резюме для бизнес-пользователя */
            summary?: string | null;
            aggregate_score?: components["schemas"]["AggregateScore"];
        };
        ClassificationResult: {
            /** @description Тип договора (услуги, поставка, подряд, аренда, NDA и др.) */
            contract_type?: string;
            /**
             * Format: float
             * @description Уровень уверенности (0.0–1.0)
             */
            confidence?: number;
        };
        KeyParameters: {
            parties?: string[];
            subject?: string | null;
            price?: string | null;
            duration?: string | null;
            penalties?: string | null;
            jurisdiction?: string | null;
        };
        RiskProfile: {
            /** @enum {string} */
            overall_level?: "high" | "medium" | "low";
            high_count?: number;
            medium_count?: number;
            low_count?: number;
        };
        Risk: {
            id?: string;
            /** @enum {string} */
            level?: "high" | "medium" | "low";
            /** @description Описание риска */
            description?: string;
            /** @description Ссылка на пункт договора */
            clause_ref?: string;
            /** @description Ссылка на норму/политику */
            legal_basis?: string;
        };
        RiskList: {
            risks?: components["schemas"]["Risk"][];
            risk_profile?: components["schemas"]["RiskProfile"];
        };
        Recommendation: {
            risk_id?: string;
            original_text?: string;
            recommended_text?: string;
            explanation?: string;
        };
        RecommendationList: {
            items?: components["schemas"]["Recommendation"][];
        };
        ContractSummaryResult: {
            /** @description Краткое резюме договора для бизнес-пользователя */
            summary?: string;
            aggregate_score?: components["schemas"]["AggregateScore"];
            key_parameters?: components["schemas"]["KeyParameters"];
        };
        AggregateScore: {
            /** Format: float */
            score?: number;
            /** @description Текстовая метка (Низкий риск / Средний риск / Высокий риск) */
            label?: string;
        };
        CompareRequest: {
            /** Format: uuid */
            base_version_id: string;
            /** Format: uuid */
            target_version_id: string;
        };
        CompareResponse: {
            /** Format: uuid */
            job_id?: string;
            /** @example QUEUED */
            status?: string;
        };
        VersionDiff: {
            /** Format: uuid */
            base_version_id?: string;
            /** Format: uuid */
            target_version_id?: string;
            text_diff_count?: number;
            structural_diff_count?: number;
            text_diffs?: {
                /** @enum {string} */
                type?: "added" | "removed" | "modified";
                path?: string;
                old_text?: string | null;
                new_text?: string | null;
            }[];
            structural_diffs?: {
                /** @enum {string} */
                type?: "added" | "removed" | "modified" | "moved";
                node_id?: string;
                old_value?: Record<string, never> | null;
                new_value?: Record<string, never> | null;
            }[];
        };
        FeedbackRequest: {
            /** @description Полезность результата проверки */
            is_useful: boolean;
            /** @description Комментарий пользователя (опционально) */
            comment?: string;
        };
        FeedbackResponse: {
            /** Format: uuid */
            feedback_id?: string;
            /** Format: date-time */
            created_at?: string;
        };
        /** @description Политика проверки организации (структура определяется OPM) */
        Policy: {
            /** Format: uuid */
            policy_id?: string;
            name?: string;
            description?: string;
            /** @description Настройки политики (определяются OPM) */
            settings?: Record<string, never>;
        };
        PolicyList: {
            items?: components["schemas"]["Policy"][];
        };
        PolicyUpdateRequest: {
            /** @description Обновлённые настройки */
            settings?: Record<string, never>;
        };
        Checklist: {
            /** Format: uuid */
            checklist_id?: string;
            contract_type?: string;
            items?: {
                id?: string;
                name?: string;
                enabled?: boolean;
                /** @enum {string} */
                severity?: "high" | "medium" | "low";
            }[];
        };
        ChecklistList: {
            items?: components["schemas"]["Checklist"][];
        };
        ChecklistUpdateRequest: {
            items?: {
                id?: string;
                enabled?: boolean;
                /** @enum {string} */
                severity?: "high" | "medium" | "low";
            }[];
        };
        UserProfile: {
            /** Format: uuid */
            user_id: string;
            /** Format: email */
            email: string;
            name: string;
            /** @enum {string} */
            role: "LAWYER" | "BUSINESS_USER" | "ORG_ADMIN";
            /** Format: uuid */
            organization_id: string;
            organization_name: string;
            permissions: components["schemas"]["UserPermissions"];
        };
        /**
         * @description Computed-флаги разрешений пользователя, агрегированные оркестратором из:
         *     (1) роли пользователя (из JWT);
         *     (2) политик организации (из OPM);
         *     (3) fallback-defaults оркестратора (env ORCH_OPM_FALLBACK_*).
         *     Frontend потребляет готовые boolean'ы — не интерпретирует политики OPM напрямую
         *     (см. Frontend/architecture/high-architecture.md §5.6, useCanExport()).
         *     Расчёт описан в high-architecture.md §6.21 (Permissions Resolver).
         */
        UserPermissions: {
            /**
             * @description Разрешён ли экспорт отчётов (PDF/DOCX) пользователю.
             *     - LAWYER, ORG_ADMIN: всегда true (безусловное разрешение по роли).
             *     - BUSINESS_USER: значение определяется политикой организации (OPM).
             *       Если OPM недоступен или политика не задана — fallback на
             *       ORCH_OPM_FALLBACK_BUSINESS_USER_EXPORT (default false, см. configuration.md).
             * @example false
             */
            export_enabled: boolean;
        };
        ErrorResponse: {
            /** @description Машиночитаемый код ошибки (e.g. FILE_TOO_LARGE, AUTH_TOKEN_EXPIRED, VALIDATION_ERROR) */
            error_code: string;
            /** @description Описание ошибки на русском языке (NFR-5.2) */
            message: string;
            /**
             * @description Дополнительные данные об ошибке. Структура зависит от error_code.
             *     Для VALIDATION_ERROR — соответствует ValidationErrorDetails (поле fields).
             *     Для FILE_TOO_LARGE — { max_size_bytes, actual_size_bytes }.
             *     Для RATE_LIMIT_EXCEEDED — { retry_after_seconds }.
             *     Для 5xx — null (внутренние детали не раскрываются клиенту).
             */
            details?: Record<string, never> | null;
            /** @description Рекомендация следующего шага для пользователя (NFR-5.2) */
            suggestion?: string | null;
            /**
             * Format: uuid
             * @description ID корреляции для обращения в поддержку
             */
            correlation_id?: string;
        };
        /**
         * @description Структура поля `details` для ErrorResponse при error_code=VALIDATION_ERROR.
         *     Гарантированный контракт для маппинга на формы (React Hook Form и др.).
         *     См. error-handling.md §3.8 для полного описания и whitelist кодов.
         */
        ValidationErrorDetails: {
            fields: components["schemas"]["ValidationFieldError"][];
        };
        ValidationFieldError: {
            /**
             * @description Путь к полю в формате JSONPath-lite (совместим с setName React Hook Form).
             *     Примеры: "title", "parties.0.name", "policy.severity".
             * @example title
             */
            field: string;
            /**
             * @description Машинный код причины. Закрытый whitelist (см. error-handling.md §3.8):
             *     REQUIRED, INVALID_FORMAT, INVALID_UUID, INVALID_DATE, INVALID_ENUM,
             *     NOT_IN_WHITELIST, TOO_SHORT, TOO_LONG, OUT_OF_RANGE, MISMATCH,
             *     DUPLICATE, INVALID_REFERENCE.
             * @example REQUIRED
             * @enum {string}
             */
            code: "REQUIRED" | "INVALID_FORMAT" | "INVALID_UUID" | "INVALID_DATE" | "INVALID_ENUM" | "NOT_IN_WHITELIST" | "TOO_SHORT" | "TOO_LONG" | "OUT_OF_RANGE" | "MISMATCH" | "DUPLICATE" | "INVALID_REFERENCE";
            /**
             * @description Человекочитаемое описание на русском (NFR-5.2). Frontend может проигнорировать в пользу собственной i18n по `code`.
             * @example Поле «Название» обязательно для заполнения.
             */
            message: string;
            /**
             * @description Параметры для интерполяции в i18n-шаблоны на стороне frontend.
             *     Примеры: для TOO_LONG — {max: 100}; для OUT_OF_RANGE — {min: 0, max: 1};
             *     для INVALID_ENUM — {allowed: ["a","b","c"]}; для MISMATCH — {other_field: "password"}.
             */
            params?: {
                [key: string]: unknown;
            } | null;
        };
    };
    responses: {
        /** @description Невалидный запрос */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Не авторизован (JWT отсутствует или невалиден) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Недостаточно прав для данной операции */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Ресурс не найден или не принадлежит организации */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Конфликт состояния (документ archived/deleted) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Превышен лимит запросов организации */
        TooManyRequests: {
            headers: {
                /** @description Секунды до следующей попытки */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description ID договора (маппится в document_id в DM) */
        ContractIdParam: string;
        VersionIdParam: string;
        PageParam: number;
        SizeParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Успешная аутентификация */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            /** @description Неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Новый access token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            /** @description Невалидный или отозванный refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Выход выполнен */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    uploadContract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description PDF-файл договора (макс. 20 МБ)
                     */
                    file: string;
                    /** @description Название договора */
                    title: string;
                };
            };
        };
        responses: {
            /** @description Договор принят в обработку */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Файл слишком большой */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неподдерживаемый формат файла */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    listContracts: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                size?: components["parameters"]["SizeParam"];
                /** @description Фильтр по статусу документа */
                status?: components["schemas"]["DocumentStatus"];
                /** @description Поиск по названию (substring match) */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список договоров */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID договора (маппится в document_id в DM) */
                contract_id: components["parameters"]["ContractIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Детали договора */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID договора (маппится в document_id в DM) */
                contract_id: components["parameters"]["ContractIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Договор удалён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    archiveContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID договора (маппится в document_id в DM) */
                contract_id: components["parameters"]["ContractIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Договор архивирован */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listVersions: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                size?: components["parameters"]["SizeParam"];
            };
            header?: never;
            path: {
                /** @description ID договора (маппится в document_id в DM) */
                contract_id: components["parameters"]["ContractIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список версий */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadNewVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID договора (маппится в document_id в DM) */
                contract_id: components["parameters"]["ContractIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description PDF-файл новой версии
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Новая версия принята в обработку */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Файл слишком большой */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID договора (маппится в document_id в DM) */
                contract_id: components["parameters"]["ContractIdParam"];
                version_id: components["parameters"]["VersionIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Детали версии с user-friendly статусом */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getVersionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID договора (маппится в document_id в DM) */
                contract_id: components["parameters"]["ContractIdParam"];
                version_id: components["parameters"]["VersionIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Текущий статус обработки */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    recheckVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID договора (маппится в document_id в DM) */
                contract_id: components["parameters"]["ContractIdParam"];
                version_id: components["parameters"]["VersionIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Повторная проверка запущена */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Текущая версия ещё обрабатывается */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    confirmContractType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID договора (маппится в document_id в DM) */
                contract_id: components["parameters"]["ContractIdParam"];
                version_id: components["parameters"]["VersionIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmTypeRequest"];
            };
        };
        responses: {
            /** @description Подтверждение принято, обработка возобновлена */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Невалидный contract_type (не соответствует whitelist LIC) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Версия не в статусе AWAITING_USER_INPUT (например, уже подтверждена, истёк таймаут или ещё анализируется) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getResults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID договора (маппится в document_id в DM) */
                contract_id: components["parameters"]["ContractIdParam"];
                version_id: components["parameters"]["VersionIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Результаты проверки (или статус обработки, если не готовы) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResults"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getRisks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID договора (маппится в document_id в DM) */
                contract_id: components["parameters"]["ContractIdParam"];
                version_id: components["parameters"]["VersionIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список рисков с пояснениями */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID договора (маппится в document_id в DM) */
                contract_id: components["parameters"]["ContractIdParam"];
                version_id: components["parameters"]["VersionIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Краткое резюме для бизнес-пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractSummaryResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getRecommendations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID договора (маппится в document_id в DM) */
                contract_id: components["parameters"]["ContractIdParam"];
                version_id: components["parameters"]["VersionIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список рекомендаций */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    compareVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID договора (маппится в document_id в DM) */
                contract_id: components["parameters"]["ContractIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Сравнение запущено */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getDiff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID договора (маппится в document_id в DM) */
                contract_id: components["parameters"]["ContractIdParam"];
                base_version_id: string;
                target_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Результат сравнения */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDiff"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Diff не найден (ещё не готов или не запускался) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    exportReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID договора (маппится в document_id в DM) */
                contract_id: components["parameters"]["ContractIdParam"];
                version_id: components["parameters"]["VersionIdParam"];
                format: "pdf" | "docx";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect на presigned URL для скачивания */
            302: {
                headers: {
                    /** @description Presigned S3 URL (TTL 5 минут) */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Отчёт ещё не готов */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    submitFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID договора (маппится в document_id в DM) */
                contract_id: components["parameters"]["ContractIdParam"];
                version_id: components["parameters"]["VersionIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Обратная связь сохранена */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listPolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Политики организации */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description OPM недоступен */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updatePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyUpdateRequest"];
            };
        };
        responses: {
            /** @description Политика обновлена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listChecklists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Чек-листы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateChecklist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                checklist_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChecklistUpdateRequest"];
            };
        };
        responses: {
            /** @description Чек-лист обновлён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Checklist"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    eventStream: {
        parameters: {
            query: {
                /** @description JWT access token */
                token: string;
                /** @description Фильтр по документу (опционально) */
                document_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Профиль пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
