package model

// ProcessingWarning represents a warning generated by a pipeline component
// about possible incompleteness or issues in document analysis.
type ProcessingWarning struct {
	Code    string          `json:"code"`
	Message string          `json:"message"`
	Stage   ProcessingStage `json:"stage"`
}
