package logger

import "context"

// contextKey is an unexported type used as a context key to prevent collisions
// with keys from other packages.
type contextKey struct{}

// RequestContext carries per-request correlation fields through context.Context.
// Loggers auto-extract these fields and prepend them to every log entry,
// eliminating the need to pass IDs explicitly at every call site.
//
// Set by the JWT auth middleware after token validation.
// Enriched by handlers when document/version/job IDs become known.
type RequestContext struct {
	// CorrelationID is the end-to-end request identifier (UUID).
	// Generated by the orchestrator on the first HTTP request and propagated
	// to downstream services (DM via HTTP header, DP via event field).
	CorrelationID string

	// OrganizationID is the tenant identifier extracted from JWT claims.
	OrganizationID string

	// UserID is the authenticated user identifier extracted from JWT claims.
	UserID string

	// DocumentID is set when the request operates on a specific document.
	// Empty for requests that are not document-scoped.
	DocumentID string

	// VersionID is set when the request operates on a specific document version.
	// Empty for requests that are not version-scoped.
	VersionID string

	// JobID is set when a processing or comparison job is involved
	// (e.g., after publishing a command to DP or receiving a DP event).
	// Empty otherwise.
	JobID string
}

// WithRequestContext returns a new context carrying the given RequestContext.
func WithRequestContext(ctx context.Context, rc RequestContext) context.Context {
	return context.WithValue(ctx, contextKey{}, rc)
}

// RequestContextFrom extracts the RequestContext from ctx.
// Returns a zero-value RequestContext if none is present.
func RequestContextFrom(ctx context.Context) RequestContext {
	rc, _ := ctx.Value(contextKey{}).(RequestContext)
	return rc
}

// WithDocumentID returns a new context with the DocumentID field updated.
// All other RequestContext fields are preserved. If no RequestContext exists
// in the parent context, a new one is created with only DocumentID set.
func WithDocumentID(ctx context.Context, documentID string) context.Context {
	rc := RequestContextFrom(ctx)
	rc.DocumentID = documentID
	return WithRequestContext(ctx, rc)
}

// WithVersionID returns a new context with the VersionID field updated.
// All other RequestContext fields are preserved.
func WithVersionID(ctx context.Context, versionID string) context.Context {
	rc := RequestContextFrom(ctx)
	rc.VersionID = versionID
	return WithRequestContext(ctx, rc)
}

// WithJobID returns a new context with the JobID field updated.
// All other RequestContext fields are preserved.
func WithJobID(ctx context.Context, jobID string) context.Context {
	rc := RequestContextFrom(ctx)
	rc.JobID = jobID
	return WithRequestContext(ctx, rc)
}
